LibMan.Presentation/Areas/Admin/Controllers/AuthorController.cs
using LibMan.Business.Author.Service;
using LibMan.Domains;
using LibMan.Presentation.Areas.Admin.ViewModels;
using LibMan.Presentation.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace LibMan.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        private readonly IAuthorService _AuthorService;

        public AuthorController(IAuthorService authorService)
        {
            _AuthorService = authorService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _AuthorService.GetAllAuthors());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id is not null)
            {
                Author targetAuthor = await _AuthorService.GetAuthorBasedOnId(Convert.ToInt32(Id));
                AuthorViewModel authorViewModel = new AuthorViewModel(targetAuthor);

                return View("Edit", authorViewModel);
            }

            return View("Edit", new AuthorViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(AuthorViewModel authorViewModel)
        {
            if(!ModelState.IsValid)
            {
                return View("Edit", authorViewModel);
            }

            bool IsSuccess = false;
            Author newAuthor = ViewModelToModel.AuthorViewModelToModel(authorViewModel);

            if (newAuthor.Id == 0)
                IsSuccess = await _AuthorService.SaveNew(newAuthor);
            else
                IsSuccess = await _AuthorService.SaveUpdate(newAuthor);

            if (!IsSuccess)
                return StatusCode(500, "A server side error occured while processing your request");

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            bool IsSuccess = await _AuthorService.RemoveAuthor(id);

            if (!IsSuccess)
            {
                return StatusCode(500, "A server side error occured while processing your request");
            }
            return RedirectToAction("Index");
        }
    }
}

LibMan.Presentation/Areas/Admin/Controllers/BookController.cs
using LibMan.Business.Author.Service;
using LibMan.Business.Book.Service;
using LibMan.Domains;
using LibMan.Presentation.Areas.Admin.ViewModels;
using LibMan.Presentation.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace LibMan.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BookController : Controller
    {
        private readonly IBookService _BookService;
        private readonly IAuthorService _AuthorService;

        public BookController(IBookService bookService, IAuthorService authorService)
        {
            _BookService = bookService;
            _AuthorService = authorService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _BookService.GetAllBooksWithAuthor());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? Id)
        {
            BookViewModel bookViewModel = new BookViewModel();
            if (Id is not null)
            {
                Book targetBook = await _BookService.GetBookBasedOnIdWithAuthor(Convert.ToInt32(Id));

                bookViewModel = new BookViewModel(targetBook);

                bookViewModel.AllAuthors = await _AuthorService.GetAllAuthors();

                return View("Edit", bookViewModel);
            }


            bookViewModel = new BookViewModel();
            bookViewModel.AllAuthors = await _AuthorService.GetAllAuthors();

            return View("Edit", bookViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(BookViewModel bookViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", bookViewModel);
            }

            bool IsSuccess = false;
            Book newBook = ViewModelToModel.BookViewModelToModel(bookViewModel);

            if (newBook.Id == 0)
                IsSuccess = await _BookService.SaveNew(newBook);
            else
                IsSuccess = await _BookService.SaveUpdate(newBook);

            if (!IsSuccess)
                return StatusCode(500, "A server side error occured while processing your request");

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            bool IsSuccess = await _BookService.RemoveBook(id);

            if (!IsSuccess)
            {
                return StatusCode(500, "A server side error occured while processing your request");
            }
            return RedirectToAction("Index");
        }
    }
}

LibMan.Presentation/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<title>LibMan - Admin</title>
	<link rel="stylesheet" href="~/admin/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
	<link href="~/Admin/assets/css/styles.css" rel="stylesheet" />
	<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
	<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
		<!-- Navbar Brand-->
		<a class="navbar-brand ps-3" href="index.html">LibMan</a>
		<!-- Sidebar Toggle-->
		<button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><svg class="svg-inline--fa fa-bars" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="bars" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"></path></svg><!-- <i class="fas fa-bars"></i> Font Awesome fontawesome.com --></button>
		<!-- Navbar Search-->
		<!-- Navbar-->

	</nav>
	<div id="layoutSidenav">
		<div id="layoutSidenav_nav">
			<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
				<div class="sb-sidenav-menu">
					<div class="nav">
						<a class="btn btn-outline-dark mt-auto text-white" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>

						<a class="btn btn-outline-dark mt-auto text-white" asp-area="Admin" asp-controller="Author" asp-action="Index">Authors</a>

						<a class="btn btn-outline-dark mt-auto text-white" asp-area="Admin" asp-controller="Book" asp-action="Index">Books</a>

						<a class="btn btn-outline-dark mt-auto text-white" asp-area="" asp-controller="Home" asp-action="Index">Homepage</a>

						<div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
							<nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
								<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
									Authentication
									<div class="sb-sidenav-collapse-arrow"><svg class="svg-inline--fa fa-angle-down" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="angle-down" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" data-fa-i2svg=""><path fill="currentColor" d="M169.4 342.6c12.5 12.5 32.8 12.5 45.3 0l160-160c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 274.7 54.6 137.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l160 160z"></path></svg><!-- <i class="fas fa-angle-down"></i> Font Awesome fontawesome.com --></div>
								</a>
								<div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
									<nav class="sb-sidenav-menu-nested nav">
										<a class="nav-link" href="login.html">Login</a>
										<a class="nav-link" href="register.html">Register</a>
										<a class="nav-link" href="password.html">Forgot Password</a>
									</nav>
								</div>
								<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
									Error
									<div class="sb-sidenav-collapse-arrow"><svg class="svg-inline--fa fa-angle-down" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="angle-down" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" data-fa-i2svg=""><path fill="currentColor" d="M169.4 342.6c12.5 12.5 32.8 12.5 45.3 0l160-160c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 274.7 54.6 137.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l160 160z"></path></svg><!-- <i class="fas fa-angle-down"></i> Font Awesome fontawesome.com --></div>
								</a>
								<div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
									<nav class="sb-sidenav-menu-nested nav">
										<a class="nav-link" href="401.html">401 Page</a>
										<a class="nav-link" href="404.html">404 Page</a>
										<a class="nav-link" href="500.html">500 Page</a>
									</nav>
								</div>
							</nav>
						</div>
					</div>
				</div>
				<div class="sb-sidenav-footer">
				</div>
			</nav>
		</div>
		<div id="layoutSidenav_content">
			<main>
				<div class="container-fluid px-4">
					@RenderBody()
				</div>
			</main>
			<footer class="py-1 bg-light mt-auto">
				<div class="container-fluid px-4">
					<div class="d-flex align-items-center justify-content-between small">
						<div class="text-muted">Copyright © Your Website 2023</div>
						<div>
							<a href="#">Privacy Policy</a>
							·
							<a href="#">Terms &amp; Conditions</a>
						</div>
					</div>
				</div>
			</footer>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
	<script src="~/Admin/assets/js/scripts.js"></script>
	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>